// this comment line is ignored
= Donald Scott Gould's Resume

== Donald Scott Gould


_<gould.dscott@gmail.com>_

**Lakewood, Colorado**

_**303-719-4160**_

  Senior level Developer with extensive knowledge of Client, Application, and Database architectures utilizing modern object oriented languages and frameworks.  Over 10 years total experience in Software & Web Development with a strong background in Hardware, Networking, Desktops and Systems Administration.

== General Computer Skills:
- Proficient in Windows and LINUX Server operating systems, such as Windows Server, and knowledge of Windows Server Core installations.
- Experience with Active Directory, including Group Policy management, user and group management, and domain administration.
- Familiarity with virtualization technologies, such as Hyper-V, VMware and Citrix.
- Strong understanding of network and security protocols, such as TCP/IP, DNS, DHCP, and firewall management.
- Knowledge of PowerShell scripting and the ability to automate tasks using scripting.
- Familiarity with backup and disaster recovery solutions, such as Backup Exec.
- Strong troubleshooting and problem-solving skills, and the ability to debug complex systems.
- Excellent communication skills and ability to collaborate with other IT team members and stakeholders.
- Willingness to learn new technologies and stay up-to-date with industry trends.


== User Interface Design for RIA 
=== (Rich Internet Applications):
- Object / Aspect Orientated ECMA JavaScript & Multi-Browser DOM.  
- ExtJS 1.x-5.x w/MVC framework, SASS / COMPASS
- FLEX / FLASH / AIR ActionScript 2 /3 Components
- MVC Frameworks / OOP Design Patterns (ExtJS MVC / Cairngorm)
- Client-side XMLHttpRequest JSON / XML Parsing, JQUERY 
- Mobile Development (Android, Sencha ExtJS / Touch, FlashLite, BREW, Windows Mobile)

== Web Application Development: 
- HTML 4/5, XHTML, CSS 3
- ColdFusion MX-10 CFMX, C#.NET, VB.NET, Client/Server COM, CFC, ASP
- Web Services Development (JSON, XML, SOAP, REST, and RSS in CFMX or C#.NET)
- UI Inspection & Debugging Tools such as FireBug, Illumination, Visual Studio Debugger
- Visual IDE: Komodo Edit, Visual Studio 2003-2012, Eclipse, CF Builder

== Database Architecture:
- MS SQL 98-2008, Oracle Servers, Data Warehouse Design & Stored Procedures

== Other Skills:
- Results orientated, hardworking, organized, multi-tasked, persistent and resilient.
- Very analytical and logical at solving complex problems involving data and technology.
- Diverse skill sets in software development process, networking and systems administration.
- Skilled at analysis, gathering requirements, architecture, prototyping and documentation.
- Ability mentor and learn new methods or languages.
- Ability to read and create blueprints, schematics, flow charts and logic diagrams
- Macromedia Fireworks, Microsoft Visio, Adobe Acrobat PDF, Microsoft Publisher


=== Education:

**ITT - _1994_**,
Bachelor of Science in Electronic Engineering - Denver, Colorado  

**Denver Tech College - _1993_**, 
Bachelor of Arts in Computer Information Science - Denver, Co

**Phoenix Institute of Technology - _1990_**, 
Certificate of Electronic Technology - Phoenix, Arizona


== Experience:

=== **GTN Technical - _Westminster, Co_**

  Systems Administrator, Sept 2022 - Apr 2023
  Provided support for the IT Support team during Windows 10 upgrade.  
  Managed and assisted in development of PowerShell scripts for deployment.

=== **Lumen Technologies - _Denver, Co_**
  
  Systems Administrator, Jul 2020 - Aug 2022
  Provided Systems Administration of Enterprise servers and support of the IT Support team.
  Assisted with SCCM management and server/desktop images.

=== **1mage Software – _Centennial, Co_**

  Windows Tech Support, Jan 2020 – Jun 2020
  Provided Windows server and desktop tech support for 1mage Imaging software Windows version.

=== **CenturyLink – _Broomfield, Co_**

  IT Support Specialist, Jan 2019 – Aug 2019
  Provided support during company-wide Windows 10 Tech Refresh in CenturyLink’s primary PC depot.  
  Worked on tickets in ServiceNow involving upgrading user’s desktops/laptops, user data migration, shipping desktop/laptop kits and general tech support issues.

=== **Colorado Oil & Gas Conservation Commission –_ Denver, Co_**
 
  Software Engineer, Jan 2018 – Sept 2018
  Legacy Silverlight application conversion to ASP.NET.

=== **Comcast – _Greenwood Village_**
  
  Software Engineer, Jul 2016 – Jul 2017
  Developed JavaScript-based SPA (Single-Paged) applications for Network Administration in EXT-JS.

=== **EzLinks Golf - _Englewood, Co_**

**Software Engineer, _Aug 2012 - Oct 2013_**

  Developed multi-platform, public facing Content Management System based website for the aggregation and sales of golf tee times for desktop and mobile systems.  Full integration with Google Maps , Google Analytics & web snapshot subsystem for compatibility with Google for Dynamic JavaScript driven AJAX sites.  Adapted Microsoft Web Services written in C# to communicate appropriately via JSON with EXTJS data connectors. All web applications were written as EXTJS JavaScript classes which was used to dynamically generate HTML appropriately for detected device. Utilized SASS/Compass for Adaptive Visual Layout.


=== U.S. General Services Administration, Public Buildings Service – Lakewood, Colorado

Web Architect, Apr 2012 – Jul 2012

  Development, integration and maintenance of various projects utilizing WCF JSON REST Web Services, EXTJS 4.x MVC, C#.NET, Office365 Online, SharePoint Online, and Windows Azure technologies.

=== Fish & Wildlife Service - Lakewood, Colorado

Web Application Developer, Oct 2010 - Jun 2011
  CF9 Web Application utilizing CF REST Web Services and ActiveDirectory LDAP for FWS Application Services Management.  Upgraded CF9 to support ColdExt for client-side HTML rendering and upgraded ColdExt to support ExtJS 3.5, exposing entire EXTJS library to CFML scripting, allowing for server-side script generation.

=== Crowley Marine - Denver, Colorado
  Software Developer, Aug 2010 - Oct 2010
  Devised a method and wrote necessary software in .NET 4.0, utilizing the Lead Tools imaging library, to extract encoded embedded resources, images, and data from existing legacy applications for use in an updated version.

Examiner.com - Denver, Colorado
Software Engineer, Mar 2009 - Jun 2010
  Acted as project lead, architect and developer for several projects including a ColdFusion based Mobile RSS Article Feed Generator and a Regression Testing Methodology involving Selenium Automated Test Suite and MXUnit Test Framework for testing and debugging of Examiner’s main site and management applications.  Created design wire frames, logic diagrams, and documented technical requirements and specifications of project designs used in creating various demos, models and simulations for Product Manager’s presentations.

Crowley Marine - Denver, Colorado
Web Developer, Dec 2008 - Mar 2009 (Part-Time)
   Worked on several short, small projects developing several Adobe Flex 3.0 applets for several customer facing websites that utilized that Cairngorm Framework, ColdFusion 8 CFCs and Flash Remoting for data communications.  

Video Professor - Lakewood, Colorado  
Software Developer, July 2007 - June 2008
  Architected and prototyped a web-based SOA Video Content Delivery System for subscribing web-based customers on desktop and mobile systems that also worked with Verizon Cell Phones, Windows Mobile PDAs / Devices, and Apple iPhone mobile devices.  An Internet Content Management System (CMS) communicated with XML Web Services, to provide pre-transcoded video and web content specific to the respective customer’s detected platform through several ColdFusion, Flex / FlashLite ActionScript 2, Visual Basic .NET and Motorola BREW based web clients.  Projects include heavy integration of ColdFusion, .NET and Flash, utilizing both .cfm (ColdFusion) and .aspx (ASP.NET) page containers.
  Development includes a VB.NET Web Service to provide Full Text Search for products and Telephone Call-Back Credit Card verification capabilities to the customer facing production web site.   Another internal VB.NET Web Service allowed for web-based authentication against a Novell NDAP Server for internal management applications.
  Gathered and analyzed business requirements from Marketing regarding Project Requirements, also provided detailed documentation and diagrams in Adobe Acrobat PDF, Microsoft Visio and Publisher for all projects involved in, including creating several prototypes and mockups for presentations for upper management highlighting newest software projects and Akamai network video bandwidth comparisons.

Resume of Donald Scott Gould Page 3


eFit Financial - Denver, Colorado
Web Application Developer, September 2004 - June 2007  
  Acted as Project Lead and mentor to 2 junior programmers while working closely with CTO and accountant to architect and design new Financial & Member Management Applications for Health Clubs.  Projects include heavy integration of ColdFusion (.cfm), ActiveX, and ASP.NET (.aspx), and C #/VB.NET.
   Re-architected and maintained an SOA Health Club Membership Access System which consisted of a web-based Subscription Management System written in ColdFusion MX 7, VB.NET Web Services, Oracle Back-end, and a Customer Check-In system written in Visual Basic 6.  The software also interfaced with on-site Card Access/Security Systems, Cash Drawers, Receipt Printers, Turnstiles, and Item Scanners.  Designed custom VoIP system for integration with eMerge Security System and internal Help Desk calls.
  Also provided phone Customer Support, Help Desk, Windows XP Desktop Support and Windows 2003 Server Administration for eFit internally, and detailed documentation and diagrams in Adobe Acrobat PDF, Microsoft Visio and Publisher for all projects involved in.
